name: tabletop-club-unofficial
title: Tabletop Club (Unofficial)
base: core24
version: 0.1.5
summary: An open-source multiplayer tabletop simulator
description: |
    Tabletop Club is an open-source multiplayer game that allows you to play your favorite tabletop games in a physics-driven 3D environment with the use of easy-to-make asset packs.

    Source: https://github.com/drwhut/tabletop-club
    Snap-Source: https://github.com/nbuechner/tabletop-club-snap

license: MIT
contact: https://github.com/nbuechner/tabletop-club-snap/issues
issues: https://github.com/nbuechner/tabletop-club-snap/issues
source-code: https://github.com/nbuechner/tabletop-club-snap
website: https://github.com/drwhut/tabletop-club

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

apps:
  tabletop-club:
    command: TabletopClub
    plugs: [home, x11, desktop, removable-media, shared-memory, opengl, network, audio-playback ]
    extensions: [ gnome ]

plugs:
  shared-memory:
    private: true

parts:
  main:
    source:
      - to amd64: https://github.com/drwhut/tabletop-club/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/TabletopClub_v${SNAPCRAFT_PROJECT_VERSION}_Linux_64.zip
      - to arm64: https://github.com/drwhut/tabletop-club/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/TabletopClub_v${SNAPCRAFT_PROJECT_VERSION}_Linux_ARM64.zip
    plugin: dump
    source-type: zip
    override-build: |
       craftctl default
       case "${CRAFT_ARCH_BUILD_FOR}" in
         amd64) BIN_ARCH=x86_64 ;;
         arm64) BIN_ARCH=arm64 ;;
       esac
       mv "${CRAFT_PART_INSTALL}/TabletopClub.${BIN_ARCH}" "${CRAFT_PART_INSTALL}/TabletopClub"
    stage-packages:
       - libgbm1
       - libgtk-3-0
       - libxrandr2
       - libnss3
       - libnotify4
       - libxss1
       - libxtst6
       - xdg-utils
       - libatspi2.0-0
       - libuuid1
       - libsecret-1-0
       - libappindicator3-1
       - desktop-file-utils
       - libvulkan1
       - mesa-vulkan-drivers

  asset-one:
    after: [ main ]
    source: .
    plugin: dump
    source-type: local
    override-build: |
       mkdir -p assets
       cd assets
       tar xf /root/project/snap/local/assets/ColorfulCards.tgz
       cd ..
       craftctl default

lint:
  ignore:
    - library

layout:
  /snap/tabletop-club-unofficial/Resources/assets:
    bind: $SNAP/assets
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
